backend:
  name: github
  repo: elaineouyangml-eng/flowanriver
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_id: magnificent-clafoutis-511fc0.netlify.app

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean, default: false}
      - {label: Tags, name: tags, widget: list}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Body, name: body, widget: markdown}
